# fly.toml app configuration file generated for rousseau-toolbox on 2025-07-17T13:40:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rousseau-toolbox'
primary_region = 'jnb'

[build]
  [build.args]
    GO_VERSION = '1.21'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
